### ISSUE TITLE
kernel_devicetree/qcom/ is missing kernel_devicetree/qcom/display/ required to build umi / cmi source!

### ISSUE THREAD

**Issue by mrslezak** [MiCode/kernel_devicetree#1]
kernel_devicetree/qcom/ is missing kernel_devicetree/qcom/display/ required to build umi / cmi source!

Sample:

EXAMPLE OF MISSING DTSIs required to build umi-q-oss source on Xiaomi_Kernel_Opensource:

/vendor/qcom/Makefile:
ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
dtbo-$(CONFIG_ARCH_KONA) +=
kona-cdp-overlay.dtbo \

kona-cdp-overlay.dts:
#include "kona-cdp.dtsi"

kona-cdp.dtsi:
#include "camera/kona-camera-sensor-cdp.dtsi" -> NOT IN MiCode/kernel_devicetree!

**Comment by cuijier** [comment]
same problem

**Comment by dataoutputstream** [comment]
xiaomi and clear works... up decent kernel source with dts ibuilted same all others brand..
