### ISSUE TITLE
lisa-r-oss Missing dtbs related to display and camera

### ISSUE THREAD

**Issue by ItsVixano** [MiCode/kernel_devicetree#16]
Looks like someone forgot to push them too

**Comment by dev-harsh1998** [comment]
Bump!

**Comment by Divyanshu-Modi** [comment]
> Looks like someone forgot to push them too

XD

**Comment by ItsVixano** [comment]
nvm, they won't care about us, closing it for good

**Comment by ghostrider-reborn** [comment]
> nvm, they won't care about us, closing it for good

eh so what, still better to leave it open, since its their issue and they havent solved it
