### ISSUE TITLE
Redmi K30 pro (lmi) 分支的device tree 好像缺文件啊？

### ISSUE THREAD

**Issue by gooyuan** [MiCode/kernel_devicetree#3]
对比 [AndroidDump/dtbo](https://github.com/AndroidDumps/redmi_lmi_dump/tree/qssi-user-10-QKQ1.191117.002-V11.0.2.0.QJKMIXM-release-keys/dtbo) 下的dtb 和 dtbo.img 的entry cout发现是有13个dtb 的，但是 lmi 分支里配置上 CONFIG_BUILD_ARM64_DT_OVERLAY=y 再加上 lmi-sm8250-overlay.dtbo 编出来的也仅仅10个entry count. 
应该是少了 xiaomi-skuld-dtbo.dts, xiaomi-urd-dtbo.dts 和 xiaomi-verthandi-dtbo.dts 相关的源码文件。 
这个与 #2 这个问题类似， 相关的data-kernel, audio-kernel, techpack, qcom-caf的补丁都打好了，使用dump 出来的dtb和dtbo.img, 是可以启动stock rom的。
如果缺少device tree, 请补充好可用的device tree, 半成品没法玩啊。 
如果是编译方式有问题， 还请不吝指出。
@ivan19871002 @mi-code @liuguo09

**Comment by ivan19871002** [comment]
这两个dtbo 不影响设备启动。已经验证过了
