### ISSUE TITLE
dts camera Umi and fix dts problems

### ISSUE THREAD

**Issue by dataoutputstream** [MiCode/kernel_devicetree#4]
Dts for camera... pff

**Comment by zhuang137** [comment]
I used your kerker source.But I meeted more issues! Do you kown how to import kona-camera to fix the problem below:
android/xiaomi/cmi/kernel/arch/arm64/boot/dts/qcom/kona.dtsi:5149:35: fatal error: camera/kona-camera.dtsi: No such file or directory
